export type WorkMedia = {
  type: "image" | "video"
  src: string
  alt?: string
}

export type Work = {
  id: number
  title: string
  category: string
  image: string
  description: string
  media?: WorkMedia[]
}

export const PORTFOLIO_WORKS: Work[] = [
  {
    id: 1,
    title: "上海地铁生产管理中心大屏",
    category: "数据大屏",
    image: "/images/work-1-new.png",
    description: "动效+多个不同版本",
    media: [
      { type: "image", src: "/images/work-1-new.png", alt: "生产管理中心大屏-首页" },
      { type: "video", src: "https://tc2aaq9ubv9eza6p.public.blob.vercel-storage.com/production-center-1.mp4", alt: "生产管理中心大屏-动效视频" },
      { type: "image", src: "/images/production-center-menu-3.0.png", alt: "生产管理中心大屏-首页菜单3.0" },
      { type: "image", src: "/images/production-center-fix-rate.png", alt: "生产管理中心大屏-首页故障修复率优化" },
      { type: "image", src: "/images/production-center-abnormal-event.png", alt: "生产管理中心大屏-发车保障异常事件" },
      { type: "image", src: "/images/production-center-construction-backup.png", alt: "生产管理中心大屏-港城车场春节专项施工备份" },
    ],
  },
  {
    id: 2,
    title: "智慧调度大屏",
    category: "数据大屏",
    image: "/images/work-zhihui-schedule.png",
    description: '上海市第二届"数建杯"数字城市建设大赛特等奖项目',
    media: [
      { type: "image", src: "/images/work-zhihui-schedule.png", alt: "智慧调度大屏-运力运量匹配分析" },
      { type: "video", src: "https://tc2aaq9ubv9eza6p.public.blob.vercel-storage.com/schedule-10.0.0.mp4", alt: "智慧调度大屏-路网监视视频" },
      { type: "video", src: "https://tc2aaq9ubv9eza6p.public.blob.vercel-storage.com/schedule-key-control.mp4", alt: "智慧调度大屏-运营重点管控视频" },
      { type: "video", src: "https://tc2aaq9ubv9eza6p.public.blob.vercel-storage.com/schedule-network-monitor.mp4", alt: "智慧调度大屏-10.0.0动效视频" },
      { type: "image", src: "/images/schedule-network-warning.png", alt: "智慧调度大屏-3x3路网大客流预警" },
      { type: "image", src: "/images/schedule-network-monitor-11.0.png", alt: "智慧调度大屏-11.0线网监视+客流信息+事件处理2条ATS" },
      { type: "image", src: "/images/schedule-warning-11.2.6.png", alt: "智慧调度大屏-11.2.6大客流预警+运力运量+方案比选+应急抢修" },
    ],
  },
  {
    id: 3,
    title: "工务数字化运维管理中心大屏",
    category: "数据大屏",
    image: "/images/work-gongwu-screen.png",
    description: "用大屏展示施工情况的日常状态模式和施工状态模式",
    media: [
      { type: "image", src: "/images/work-gongwu-screen.png", alt: "工务数字化运维管理中心大屏-首页" },
      { type: "image", src: "/images/gongwu-daily-1.png", alt: "工务数字化运维管理中心大屏-日常生产大屏" },
      { type: "image", src: "/images/gongwu-daily-2.0.png", alt: "工务数字化运维管理中心大屏-日常生产大屏2.0" },
      { type: "image", src: "/images/gongwu-construction-status.png", alt: "工务数字化运维管理中心大屏-施工情况" },
    ],
  },
  {
    id: 14,
    title: "同济大学附属中学",
    category: "数据大屏",
    image: "/images/tongji-class-analysis-25.6.28.png",
    description: "数据可视化校园+AI创作",
    media: [
      { type: "image", src: "/images/tongji-class-analysis-25.6.28.png", alt: "同济大学附属中学-班级分析25.6.28" },
      { type: "image", src: "/images/tongji-health-25.6.28.png", alt: "同济大学附属中学-体质健康25.6.28" },
      { type: "image", src: "/images/tongji-vision-25.6.28.png", alt: "同济大学附属中学-视力大屏25.6.28" },
      { type: "image", src: "/images/tongji-score-analysis-25.6.28.png", alt: "同济大学附属中学-成绩分析25.6.28" },
      { type: "image", src: "/images/tongji-campus.jpg", alt: "同济大学附属中学-校园展示" },
    ],
  },
  {
    id: 15,
    title: "校园数据门户",
    category: "数据大屏",
    image: "/images/campus-portal-06.jpg",
    description: "校园数据可视化门户大屏",
    media: [
      { type: "image", src: "/images/campus-portal-06.jpg", alt: "校园数据门户-页面6" },
      { type: "image", src: "/images/campus-portal-01.png", alt: "校园数据门户-页面1" },
      { type: "image", src: "/images/campus-portal-02.png", alt: "校园数据门户-页面2" },
      { type: "image", src: "/images/campus-portal-03.png", alt: "校园数据门户-页面3" },
      { type: "image", src: "/images/campus-portal-04.png", alt: "校园数据门户-页面4" },
      { type: "image", src: "/images/campus-portal-05.png", alt: "校园数据门户-页面5" },
      { type: "image", src: "/images/campus-portal-07.png", alt: "校园数据门户-页面7" },
      { type: "image", src: "/images/campus-portal-08.png", alt: "校园数据门户-页面8" },
      { type: "image", src: "/images/campus-portal-09.png", alt: "校园数据门户-页面9" },
      { type: "image", src: "/images/campus-portal-10.png", alt: "校园数据门户-页面10" },
    ],
  },
  {
    id: 16,
    title: "中国风大屏",
    category: "数据大屏",
    image: "/images/chinese-screen-04.jpg",
    description: "中国风可视化大屏展示",
    media: [
      { type: "image", src: "/images/chinese-screen-04.jpg", alt: "中国风大屏-页面4" },
      { type: "image", src: "/images/chinese-screen-01.jpg", alt: "中国风大屏-页面1" },
      { type: "image", src: "/images/chinese-screen-02.jpg", alt: "中国风大屏-页面2" },
      { type: "image", src: "/images/chinese-screen-03.jpg", alt: "中国风大屏-页面3" },
      { type: "image", src: "/images/chinese-screen-05.jpg", alt: "中国风大屏-页面5" },
    ],
  },
  {
    id: 18,
    title: "大众汽车座椅控制系统",
    category: "移动端",
    image: "/images/mobile-vw-first-page.jpg",
    description: "车载座椅控制系统移动端交互设计",
    media: [
      { type: "image", src: "/images/mobile-vw-first-page.jpg", alt: "大众汽车座椅控制系统-第一页" },
      { type: "image", src: "/images/mobile-vw-01.jpg", alt: "大众汽车座椅控制系统-共享商城" },
      { type: "image", src: "/images/mobile-vw-02.jpg", alt: "大众汽车座椅控制系统-开发者模式" },
      { type: "image", src: "/images/mobile-vw-03.jpg", alt: "大众汽车座椅控制系统-页面1" },
      { type: "image", src: "/images/mobile-vw-04.jpg", alt: "大众汽车座椅控制系统-页面2" },
      { type: "image", src: "/images/mobile-vw-05.jpg", alt: "大众汽车座椅控制系统-页面3" },
    ],
  },
  {
    id: 17,
    title: "万房网",
    category: "移动端",
    image: "/images/mobile-wfw-01.jpg",
    description: "房产信息移动端产品设计",
    media: [
      { type: "image", src: "/images/mobile-wfw-01.jpg", alt: "万房网-首页" },
      { type: "image", src: "/images/mobile-wfw-02.jpg", alt: "万房网-首页优惠券弹窗" },
      { type: "image", src: "/images/mobile-wfw-03.jpg", alt: "万房网-新房" },
      { type: "image", src: "/images/mobile-wfw-04.jpg", alt: "万房网-二手房楼盘列表" },
      { type: "image", src: "/images/mobile-wfw-05.jpg", alt: "万房网-房价计算器商业贷款" },
      { type: "image", src: "/images/mobile-wfw-06.jpg", alt: "万房网-热度柱状图" },
      { type: "image", src: "/images/mobile-wfw-07.jpg", alt: "万房网-搜索" },
      { type: "image", src: "/images/mobile-wfw-08.jpg", alt: "万房网-关于我们" },
      { type: "image", src: "/images/mobile-wfw-09.jpg", alt: "万房网-详情页" },
      { type: "image", src: "/images/mobile-wfw-10.jpg", alt: "万房网-行业动态详情" },
      { type: "image", src: "/images/mobile-wfw-11.jpg", alt: "万房网-预约看房" },
      { type: "image", src: "/images/mobile-wfw-12.jpg", alt: "万房网-户型图" },
    ],
  },
  {
    id: 19,
    title: "竹智方小程序",
    category: "移动端",
    image: "/images/mobile-zzf-03.png",
    description: "小程序产品设计与视觉体验优化",
    media: [
      { type: "image", src: "/images/mobile-zzf-03.png", alt: "竹智方小程序-页面3" },
      { type: "image", src: "/images/mobile-zzf-02.png", alt: "竹智方小程序-页面2" },
      { type: "image", src: "/images/mobile-zzf-04.png", alt: "竹智方小程序-页面4" },
      { type: "image", src: "/images/mobile-zzf-05.png", alt: "竹智方小程序-页面5" },
      { type: "image", src: "/images/mobile-zzf-06.png", alt: "竹智方小程序-页面6" },
      { type: "image", src: "/images/mobile-zzf-07.png", alt: "竹智方小程序-页面7" },
      { type: "image", src: "/images/mobile-zzf-01.png", alt: "竹智方小程序-页面1" },
    ],
  },
  {
    id: 20,
    title: "运维信息化系统",
    category: "移动端",
    image: "/images/mobile-ops-01.png",
    description: "运维移动端信息化管理系统",
    media: [
      { type: "image", src: "/images/mobile-ops-01.png", alt: "运维信息化系统-页面1" },
      { type: "image", src: "/images/mobile-ops-03.png", alt: "运维信息化系统-页面3" },
      { type: "image", src: "/images/mobile-ops-04.png", alt: "运维信息化系统-页面4" },
      { type: "image", src: "/images/mobile-ops-05.png", alt: "运维信息化系统-页面5" },
      { type: "image", src: "/images/mobile-ops-06.png", alt: "运维信息化系统-页面6" },
      { type: "image", src: "/images/mobile-ops-07.png", alt: "运维信息化系统-页面7" },
      { type: "image", src: "/images/mobile-ops-08.png", alt: "运维信息化系统-页面8" },
      { type: "image", src: "/images/mobile-ops-02.png", alt: "运维信息化系统-页面2" },
    ],
  },
  {
    id: 4,
    title: "地铁安检项目",
    category: "后台",
    image: "/images/work-subway-security-admin.png",
    description: "组件库高效完成，日间模式+夜间模式一键切换",
    media: [
      { type: "image", src: "/images/work-subway-security-admin.png", alt: "地铁安检项目-首页" },
      { type: "video", src: "https://tc2aaq9ubv9eza6p.public.blob.vercel-storage.com/security-switch.mp4", alt: "地铁安检项目-一键切换视频" },
      { type: "image", src: "/images/security-network-light-1.2.png", alt: "地铁安检项目-线网可视化浅色1.2" },
      { type: "image", src: "/images/security-home-simple.png", alt: "地铁安检项目-首页简化版" },
      { type: "image", src: "/images/security-assets.png", alt: "地铁安检项目-设备资产" },
      { type: "image", src: "/images/security-visual-resource-3.png", alt: "地铁安检项目-可视化资源3" },
      { type: "image", src: "/images/security-package-query-3-backup2.png", alt: "地铁安检项目-包裹数据查询3备份2" },
      { type: "image", src: "/images/security-package-query.png", alt: "地铁安检项目-包裹数据查询" },
    ],
  },
  {
    id: 5,
    title: "大数据中心看板",
    category: "网页",
    image: "/images/work-bigdata-web-dashboard.png",
    description: "复杂网站作品示例",
    media: [
      { type: "image", src: "/images/work-bigdata-web-dashboard.png", alt: "大数据中心看板-封面" },
      { type: "image", src: "/images/bigdata-market-indicator.png", alt: "大数据中心看板-集团市场经营指标看板" },
      { type: "image", src: "/images/bigdata-operation-cost.jpg", alt: "大数据中心看板-集团运营成本收支看板" },
      { type: "image", src: "/images/bigdata-power-strategy-dark.jpg", alt: "大数据中心看板-供电分公司战略指标深蓝" },
      { type: "image", src: "/images/bigdata-device-power-assessment.jpg", alt: "大数据中心看板-设施设备看板供电状态评估" },
      { type: "image", src: "/images/bigdata-operation-cost.jpg", alt: "大数据中心看板-集团运营成本收支看板-重复页" },
      { type: "image", src: "/images/bigdata-major-operation-guarantee-2.0.jpg", alt: "大数据中心看板-重大运营保障2.0" },
      { type: "image", src: "/images/bigdata-passenger-change-2.0.jpg", alt: "大数据中心看板-客运量变化特点2.0" },
      { type: "image", src: "/images/bigdata-network-quality-event-2.1.jpg", alt: "大数据中心看板-线网质量事件2.1" },
      { type: "image", src: "/images/bigdata-operation-overview.jpg", alt: "大数据中心看板-运营管理工作情况" },
      { type: "image", src: "/images/bigdata-operation-tip-2.0.jpg", alt: "大数据中心看板-运营生产工作提示2.0" },
    ],
  },
  {
    id: 6,
    title: "上海地铁建设集团",
    category: "网页",
    image: "/images/work-shmetro-construction.png",
    description: "图表数据统计类网站",
    media: [
      { type: "image", src: "/images/work-shmetro-construction.png", alt: "上海地铁建设集团-综合看板" },
      { type: "image", src: "/images/construction-progress-2.png", alt: "上海地铁建设集团-指标看板进度2" },
      { type: "image", src: "/images/construction-progress.png", alt: "上海地铁建设集团-指标看板进度" },
      { type: "image", src: "/images/construction-invest-backup-2x.png", alt: "上海地铁建设集团-指标看板投资备份" },
      { type: "image", src: "/images/construction-invest-popup-2x.png", alt: "上海地铁建设集团-指标看板投资弹窗" },
    ],
  },
  {
    id: 7,
    title: "项目管理后台",
    category: "后台",
    image: "/images/work-project-admin.png",
    description: "一个产品多个项目复用，节约项目成本",
    media: [
      { type: "image", src: "/images/work-project-admin.png", alt: "项目管理后台-首页" },
      { type: "image", src: "/images/project-admin-data-maintain.png", alt: "项目管理后台-数据维护新增基本信息" },
      { type: "image", src: "/images/project-admin-device-visual.png", alt: "项目管理后台-设备项目可视化" },
      { type: "image", src: "/images/project-admin-home-backup.png", alt: "项目管理后台-首页备份" },
      { type: "image", src: "/images/project-admin-flow-query.png", alt: "项目管理后台-验工计价流程查询" },
      { type: "image", src: "/images/project-admin-data-query.png", alt: "项目管理后台-验工计价数据查询" },
      { type: "image", src: "/images/project-admin-ledger-procurement.png", alt: "项目管理后台-项目台账详情采购情况" },
      { type: "image", src: "/images/project-admin-ledger-progress-return.png", alt: "项目管理后台-项目台账详情进度回款" },
      { type: "image", src: "/images/project-admin-ledger-weekly-plan.png", alt: "项目管理后台-项目台账详情周度计划" },
      { type: "image", src: "/images/project-admin-ledger-budget-popup.png", alt: "项目管理后台-项目台账详情预算执行弹窗" },
    ],
  },
  {
    id: 8,
    title: "维保在线学习平台",
    category: "网页",
    image: "/images/work-weibao-learning.png",
    description: "课程平台网站及后台管理",
    media: [
      { type: "image", src: "/images/work-weibao-learning.png", alt: "维保在线学习平台-课程页" },
      { type: "image", src: "/images/weibao-learning-login.png", alt: "维保在线学习平台-登录页" },
      { type: "image", src: "/images/weibao-learning-home.png", alt: "维保在线学习平台-首页" },
      { type: "image", src: "/images/weibao-learning-requirement-list.png", alt: "维保在线学习平台-需求管理数据列表" },
    ],
  },
  {
    id: 22,
    title: "数字教育",
    category: "网页",
    image: "/images/web-digital-education-cover.jpg",
    description: "数据中心产品介绍与教育场景可视化展示",
    media: [
      { type: "image", src: "/images/web-digital-education-cover.jpg", alt: "数字教育-数据中心产品介绍" },
    ],
  },
  {
    id: 9,
    title: "UI设计规范文件",
    category: "设计规范",
    image: "/images/work-ui-spec-cover.png",
    description: "把项目做成产品，\n把一次性的设计图转化为公司的设计资产。",
    media: [
      { type: "image", src: "/images/ui-spec-01-cover.png", alt: "UI设计规范文件-封面" },
      { type: "image", src: "/images/ui-spec-02-grid.png", alt: "UI设计规范文件-栅格布局" },
      { type: "image", src: "/images/ui-spec-03-layout.png", alt: "UI设计规范文件-界面布局" },
      { type: "image", src: "/images/ui-spec-04-shadow.png", alt: "UI设计规范文件-投影层级" },
      { type: "image", src: "/images/ui-spec-05-color-rule.png", alt: "UI设计规范文件-色彩规范" },
      { type: "image", src: "/images/ui-spec-06-color-usage.png", alt: "UI设计规范文件-色彩使用" },
      { type: "image", src: "/images/ui-spec-07-menu-framework.png", alt: "UI设计规范文件-菜单框架" },
      { type: "image", src: "/images/ui-spec-08-font-rule.png", alt: "UI设计规范文件-字体规范" },
      { type: "image", src: "/images/ui-spec-09-font-usage.png", alt: "UI设计规范文件-字体使用" },
      { type: "image", src: "/images/ui-spec-10-button-variant.png", alt: "UI设计规范文件-按钮变体" },
      { type: "image", src: "/images/ui-spec-11-switch-group.png", alt: "UI设计规范文件-切换框组" },
      { type: "image", src: "/images/ui-spec-12-table-layout.png", alt: "UI设计规范文件-表格自动化布局" },
      { type: "image", src: "/images/ui-spec-13-chart.png", alt: "UI设计规范文件-实际应用图表" },
      { type: "image", src: "/images/ui-spec-14-composite.png", alt: "UI设计规范文件-实际应用复合组件" },
      { type: "image", src: "/images/ui-spec-15-standard-page.png", alt: "UI设计规范文件-实际应用标准化页面" },
      { type: "image", src: "/images/ui-spec-16-style-explore.png", alt: "UI设计规范文件-风格探索" },
      { type: "image", src: "/images/ui-spec-17-framework-explore.png", alt: "UI设计规范文件-框架探索" },
    ],
  },
  {
    id: 10,
    title: "地铁车联网",
    category: "后台",
    image: "/images/work-metro-iot.png",
    description: "深色+浅色+炫酷动效",
    media: [
      { type: "image", src: "/images/work-metro-iot.png", alt: "地铁车联网-首页" },
      { type: "image", src: "/images/metro-iot-map-mode-3.2.png", alt: "地铁车联网-地图模式3.2" },
      { type: "image", src: "/images/metro-iot-card-mode-event-popup.png", alt: "地铁车联网-卡片模式事件中心弹窗" },
      { type: "image", src: "/images/metro-iot-train-mode-3.0.png", alt: "地铁车联网-列车模式3.0" },
      { type: "image", src: "/images/metro-iot-map-mode-4.0-dark-backup-2.png", alt: "地铁车联网-地图模式4.0深色备份2" },
      { type: "image", src: "/images/metro-iot-map-mode-4.0-dark-backup-3.png", alt: "地铁车联网-地图模式4.0深色备份3" },
    ],
  },
  {
    id: 11,
    title: "维保首页看板",
    category: "后台",
    image: "/images/work-weibao-dashboard.png",
    description: "高保真交互演示，3种颜色以供备选",
    media: [
      { type: "image", src: "/images/work-weibao-dashboard.png", alt: "维保首页看板-首页供电" },
      { type: "image", src: "/images/weibao-dashboard-vehicle.png", alt: "维保首页看板-首页车辆" },
    ],
  },
  {
    id: 12,
    title: "运维看板",
    category: "后台",
    image: "/images/work-ops-dashboard-v2.png",
    description: "高保真交互演示，3种颜色以供备选深色+浅色+炫酷动效",
    media: [
      { type: "image", src: "/images/work-ops-dashboard-v2.png", alt: "运维看板-首页" },
      { type: "video", src: "/videos/opsv2-home.mp4", alt: "运维看板-首页动效视频" },
      { type: "image", src: "/images/opsv2-shou-light.png", alt: "运维看板-收浅色" },
      { type: "image", src: "/images/opsv2-shou.png", alt: "运维看板-收" },
      { type: "image", src: "/images/opsv2-yong-note.png", alt: "运维看板-用备注" },
      { type: "image", src: "/images/opsv2-zhi.png", alt: "运维看板-治" },
      { type: "image", src: "/images/opsv2-guan.png", alt: "运维看板-管" },
      { type: "image", src: "/images/opsv2-cun.png", alt: "运维看板-存" },
      { type: "image", src: "/images/opsv2-image1.png", alt: "运维看板-图片1" },
    ],
  },
  {
    id: 13,
    title: "智慧运维管理平台-科研项目",
    category: "后台",
    image: "/images/work-smart-ops-research.png",
    description: "运维后台项目+项目LOGO设计思路",
    media: [
      { type: "image", src: "/images/work-smart-ops-research.png", alt: "智慧运维管理平台-首页总览" },
      { type: "image", src: "/images/smartops-business-monitoring.png", alt: "智慧运维管理平台-业务监控系统" },
      { type: "image", src: "/images/smartops-business-observe.png", alt: "智慧运维管理平台-业务监视系统" },
      { type: "image", src: "/images/smartops-cloud-overview-2.0.png", alt: "智慧运维管理平台-云资源总览2.0" },
      { type: "image", src: "/images/smartops-logo.png", alt: "智慧运维平台logo" },
    ],
  },
  {
    id: 21,
    title: "基线版本AI项目",
    category: "后台",
    image: "/images/ai-baseline-app-center-3.png",
    description: "AI应用中心与问答/游戏能力后台",
    media: [
      { type: "image", src: "/images/ai-baseline-app-center-3.png", alt: "基线版本AI-应用中心3" },
      { type: "image", src: "/images/ai-baseline-app-recommend-2.png", alt: "基线版本AI-应用推荐2" },
      { type: "image", src: "/images/ai-baseline-answer-loading-5.png", alt: "基线版本AI-开始回答思考中正文加载中5" },
      { type: "image", src: "/images/ai-baseline-answer-done.png", alt: "基线版本AI-开始回答思考完成" },
      { type: "image", src: "/images/ai-baseline-file-qa.png", alt: "基线版本AI-开始回答文件问答" },
      { type: "image", src: "/images/ai-baseline-data-report-2.png", alt: "基线版本AI-数据上报2" },
      { type: "image", src: "/images/ai-baseline-game-list-subject-modal.png", alt: "基线版本AI-游戏列表切换学段学科弹窗" },
      { type: "image", src: "/images/ai-baseline-game-list-dev-modal.png", alt: "基线版本AI-游戏列表游戏正在开发中弹窗" },
      { type: "image", src: "/images/ai-baseline-game-list-review-modal.png", alt: "基线版本AI-游戏列表评价弹框" },
      { type: "image", src: "/images/ai-baseline-game-list.png", alt: "基线版本AI-游戏列表" },
      { type: "image", src: "/images/ai-baseline-game-list-3.png", alt: "基线版本AI-游戏列表3" },
    ],
  },
]

export function getFeaturedWorks(): Work[] {
  const featuredIds = [1, 2, 3]
  return PORTFOLIO_WORKS.filter((work) => featuredIds.includes(work.id))
}
